In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings\annotations\cleaning_report.csv")
df.head()

,clip_id,reason,text
0,clip_0005,empty_transcript,"8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
1,clip_0027,filler_only: 'and',and
2,clip_0050,filler_only: 'the',the
3,clip_0096,"repeated_words: 'good good,' x112","good, good, good, good, good, good, good, good..."
4,clip_0099,empty_transcript,"4, 5, 4, 4, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5..."

In [3]:
df1=pd.read_csv(r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings\annotations\labels_clean.csv")
df1.head()

,clip_id,text_label,text_confidence,acoustic_label,acoustic_confidence,final_label,confidence,flagged_for_review,acoustic_features
0,clip_0000,Calm,0.8277,Calm,0.65,Calm,0.7566,False,"{""mean_pitch"": 102.89, ""pitch_range"": 12.49, ""..."
1,clip_0001,Calm,0.4994,Calm,0.65,Calm,0.5596,True,"{""mean_pitch"": 104.91, ""pitch_range"": 40.43, ""..."
2,clip_0002,Calm,0.9339,Calm,0.65,Calm,0.8203,False,"{""mean_pitch"": 111.0, ""pitch_range"": 8.38, ""pi..."
3,clip_0003,Calm,0.8290,Calm,0.65,Calm,0.7574,False,"{""mean_pitch"": 106.83, ""pitch_range"": 37.18, ""..."
4,clip_0004,Calm,0.8896,High Stress,0.70,Calm,0.5338,True,"{""mean_pitch"": 105.66, ""pitch_range"": 175.83, ..."

In [4]:
df2=pd.read_csv(r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings\annotations\labels.csv")
df2.head()

,clip_id,text_label,text_confidence,acoustic_label,acoustic_confidence,final_label,confidence,flagged_for_review,acoustic_features
0,clip_0000,Calm,0.8277,Calm,0.65,Calm,0.7566,False,"{""mean_pitch"": 102.89, ""pitch_range"": 12.49, ""..."
1,clip_0001,Calm,0.4994,Calm,0.65,Calm,0.5596,False,"{""mean_pitch"": 104.91, ""pitch_range"": 40.43, ""..."
2,clip_0002,Calm,0.9339,Calm,0.65,Calm,0.8203,False,"{""mean_pitch"": 111.0, ""pitch_range"": 8.38, ""pi..."
3,clip_0003,Calm,0.8290,Calm,0.65,Calm,0.7574,False,"{""mean_pitch"": 106.83, ""pitch_range"": 37.18, ""..."
4,clip_0004,Calm,0.8896,High Stress,0.70,Urgent,0.5338,False,"{""mean_pitch"": 105.66, ""pitch_range"": 175.83, ..."

In [5]:
df3=pd.read_csv(r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings\annotations\preprocessed_text_clean.csv")
df3.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ritarshi Roy\\OneDrive\\Desktop\\Projects\\F1 Recordings\\annotations\\preprocessed_text_clean.csv'

In [ ]:
df4=pd.read_csv(r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings\annotations\preprocessed_text.csv")
df4.head()

,clip_id,raw_text,clean_text,tokens,lemmas,stopword_counts,word_count,negation_count,question_count,avg_word_length,is_empty
0,clip_0000,"Okay, we'll switch off the pit line for a half...","okay, we'll switch off the pit line for a half...","[""okay"", "","", ""we"", ""'ll"", ""switch"", ""off"", ""t...","[""okay"", "","", ""we"", ""'ll"", ""switch"", ""off"", ""t...","{""off"": 1, ""the"": 1, ""for"": 1, ""a"": 1, ""we"": 1}",11,0,0,3.545,False

In [ ]:
df5=pd.read_csv(r"data/clip_manifest.csv")
df5.head()

,clip_id,source_file,start_sec,end_sec,duration_sec
0,clip_0000,Alexander_Albon_Full_Qualifying_Team_Radio___2...,0.224,2.592,2.368
1,clip_0001,Alexander_Albon_Full_Qualifying_Team_Radio___2...,15.296,18.784,3.488
2,clip_0002,Alexander_Albon_Full_Qualifying_Team_Radio___2...,20.512,22.528,2.016
3,clip_0003,Alexander_Albon_Full_Qualifying_Team_Radio___2...,35.744,37.824,2.080
4,clip_0004,Alexander_Albon_Full_Qualifying_Team_Radio___2...,38.688,58.688,20.000

In [ ]:
df6=pd.read_csv(r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings\data\transcription_log.csv")
df6.head()

,clip_id,text,word_count,language,is_empty,is_very_short
0,clip_0000,"Okay, we'll switch off the pit line for a half...",11,en,False,False

## Manual Review — Flagged Clips

Run the cell below. For each clip:
1. Listen to the audio
2. Read the transcript
3. Click the correct emotion label

Progress is saved to `labels.csv` after every click. If you close and reopen the notebook, just re-run the cell — it automatically picks up where you left off.

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, Audio, clear_output
import os

BASE        = r"C:\Users\Ritarshi Roy\OneDrive\Desktop\Projects\F1 Recordings"
LABELS_CSV  = os.path.join(BASE, "annotations", "labels.csv")
TEXT_CSV    = os.path.join(BASE, "annotations", "preprocessed_text.csv")
CLEANED_DIR = os.path.join(BASE, "data", "cleaned")
CLIPS_DIR   = os.path.join(BASE, "data", "clips")

# Reload CSV fresh so resuming works correctly after a break
labels_df = pd.read_csv(LABELS_CSV)
text_df   = pd.read_csv(TEXT_CSV)[["clip_id", "raw_text"]]
df        = labels_df.merge(text_df, on="clip_id", how="left")

flagged = df[df["flagged_for_review"] == True].reset_index(drop=True)
total   = len(flagged)

current = [0]

def get_audio_path(clip_id):
    for folder in [CLEANED_DIR, CLIPS_DIR]:
        path = os.path.join(folder, f"{clip_id}.wav")
        if os.path.exists(path):
            return path
    return None

def save_label(clip_id, label):
    df_save = pd.read_csv(LABELS_CSV)
    df_save.loc[df_save["clip_id"] == clip_id, "final_label"]        = label
    df_save.loc[df_save["clip_id"] == clip_id, "flagged_for_review"] = False
    df_save.to_csv(LABELS_CSV, index=False)

def show_clip(idx):
    clear_output(wait=True)

    if total == 0:
        print("All flagged clips have already been reviewed!")
        return

    if idx >= total:
        print(f"Done! All {total} flagged clips reviewed.")
        return

    row       = flagged.iloc[idx]
    clip_id   = row["clip_id"]
    auto_lbl  = row["final_label"]
    conf      = row["confidence"]
    transcript = row["raw_text"] if pd.notna(row.get("raw_text")) else "(no transcript)"

    progress = widgets.IntProgress(
        value=idx, min=0, max=total,
        description=f"{idx}/{total}",
        style={"bar_color": "#4a90d9"},
        layout=widgets.Layout(width="500px")
    )

    info = widgets.HTML(f"""
        <h3 style="margin-bottom:4px">{clip_id}</h3>
        <p style="margin:4px 0">
            <b>Auto-label:</b> {auto_lbl} &nbsp;|&nbsp;
            <b>Confidence:</b> {conf:.2f}
        </p>
        <p style="margin:4px 0"><b>Transcript:</b></p>
        <div style="background:#f0f4f8;padding:10px;border-radius:6px;
                    max-width:620px;font-size:14px;line-height:1.5">
            {transcript}
        </div>
        <p style="margin-top:10px"><b>Choose the correct label:</b></p>
    """)

    audio_path = get_audio_path(clip_id)
    audio_widget = Audio(filename=audio_path) if audio_path else widgets.Label("(audio not found)")

    btn_calm       = widgets.Button(description="Calm",        button_style="info",    layout=widgets.Layout(width="130px"))
    btn_frustrated = widgets.Button(description="Frustrated",  button_style="warning", layout=widgets.Layout(width="130px"))
    btn_stress     = widgets.Button(description="High Stress", button_style="danger",  layout=widgets.Layout(width="130px"))
    btn_urgent     = widgets.Button(description="Urgent",      button_style="danger",  layout=widgets.Layout(width="130px"))
    btn_skip       = widgets.Button(description="Skip",        button_style="",        layout=widgets.Layout(width="130px"))

    def make_label_handler(label):
        def handler(b):
            save_label(clip_id, label)
            current[0] += 1
            show_clip(current[0])
        return handler

    def on_skip(b):
        current[0] += 1
        show_clip(current[0])

    btn_calm.on_click(make_label_handler("Calm"))
    btn_frustrated.on_click(make_label_handler("Frustrated"))
    btn_stress.on_click(make_label_handler("High Stress"))
    btn_urgent.on_click(make_label_handler("Urgent"))
    btn_skip.on_click(on_skip)

    buttons = widgets.HBox([btn_calm, btn_frustrated, btn_stress, btn_urgent, btn_skip],
                           layout=widgets.Layout(gap="8px", margin="4px 0"))

    display(progress, info, audio_widget, buttons)

show_clip(current[0])

All flagged clips have already been reviewed!